CREATE SCHEMA MENSCH_MASCHINE;

CREATE ROLE APP_ROLE;
GRANT ALL ON SCHEMA MENSCH_MASCHINE TO APP_ROLE;

CREATE USER mensch_maschine_app PASSWORD 'mensch_maschine_app';
GRANT APP_ROLE TO mensch_maschine_app;

SET SCHEMA MENSCH_MASCHINE;
CREATE TABLE TASKS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO TASKS (NAME) values ('Danilo');
COMMIT;